version: "3"

services:
  research:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
